version: "3"

services:
  apache:
    image: php:8.3-apache
    container_name: apache-container
    restart: always
    ports:
      - "${APACHE_PORT}:80"
    environment:
      XDEBUG_MODE: debug
    volumes:
      - "./html:/var/www/html"
      - "./src:/var/www/src"
      - "./vendor:/var/www/vendor"
      - ".env:/var/www/.env"
#      - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libpq-dev &&
        docker-php-ext-install pdo_pgsql &&
        a2enmod rewrite &&
        apache2-foreground
      "
    #        pecl install xdebug &&
    #        docker-php-ext-enable xdebug &&
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:16.2
    container_name: postgres-container
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config:/docker-entrypoint-initdb.d
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin-container
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    command: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/init_pgadmin.sh & /entrypoint.sh"]
    networks:
      - network

networks:
  network:
    driver: bridge